### PR TITLE
Destroy existing Chef handles prior to attempting upgrade on Windows

### LINKED ISSUE #110: Unsuccessful upgrades when other processes have open handles in chef_install_dir
### Cookbook version
3.2.6

### Platform Details
Windows

### Scenario:
A frequent problem we encounter when trying to use this cookbook is the upgrade script failing to remove the chef install dir due to open file handles. This is usually because of AV/endpoint protection or similar software.

This causes the upgrade script to fail and chef-client is left in an inoperable state requiring manual intervention.

### Steps to Reproduce:
Open a file in the chef install dir in another process and run the cookbook.

### PR DESCRIPTION
**Pull request by stuartpreston**
Signed-off-by: Stuart Preston <stuart@chef.io>

### Description

This change brings in the use of the Sysinternals tool, `handle.exe` (see https://docs.microsoft.com/en-us/sysinternals/downloads/handle) combined with some utility PowerShell code in order to reduce the number of locked files immediately prior to the installation of a new Chef Client version.

The appropriate Handle for the target architecture will be downloaded and copied to the Chef Client cache folder during the cookbook's execution.  If you are in an airgapped environment, you will need to either download the contents of [Handle.zip](https://download.sysinternals.com/files/Handle.zip) manually to `Chef::Config[:file_cache_path]` and the local version will be used instead of downloaded, alternatively host [Handle.zip](https://download.sysinternals.com/files/Handle.zip) yourself and override the attribute `['chef_client_updater']['handle_zip_download_url']` with the location.

To reproduce a locked file on Windows for testing:

1. Open `cmd.exe`
2.  `cd \opscode\chef`
3. `notepad Gemfile` (or other file)
4. Execute this cookbook's default recipe (e.g. `chef-client -z -r chef_client_updater`)

### Issues Resolved

Backstory #67 #69
Fixes #110 #74 #112
Supercedes PR #111

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by kitforbes** [comment]
Thanks for putting this together. I've just tested upgrading Chef client "12.21.4" to "13.8.5" on Windows Server 2012R2 where the `chef-log.dll` was previously being locked by the `DHCP Client` (Due to the Splunk Forwarder, I believe) and the upgrade was successful.

For reference, the log file content contains:

```
[*] Destroying open Chef handles.
[*] Completed destroying open Chef handles.

ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     0.0        Omnitruck                           {Get-ProjectMetada...
SUCCESS: The scheduled task "Chef_upgrade" was successfully deleted.
```

The only suggestion I would make is to rename the scheduled task to `chef-client_upgrade` to match the default name of the Chef client task, `chef-client`. Not an important thing, so I don't mind if it stays as it is!

**Comment by tas50** [comment]
@stuartpreston There's a simple cookstyle fix that will get this green. Make sure to install the latest cookstyle first.

File: recipes/default.rb [hunk 1]
```diff
@@ -17,6 +17,16 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# This resource will download the Handle.exe tool required from the specified
+# URL. If in an airgapped environment, you will need to either override the
+# ['chef_client_updater']['handle_download_url'] attribute or alternatively
+# ensure the executable files are extracted to Chef::Config[:file_cache_path]
+remote_file "#{Chef::Config[:file_cache_path]}/handle.zip" do
```
Comment (tas50) [inline recipes/default.rb]: This logic should go into the updater resource so that users can use it without the need for the recipe. The attribute should also be a property on the resource instead of a node attribute.

**Comment by stuartpreston** [comment]
@tas50 @btm @Happycoil Thanks for all the feedback so far, after a review we decided to move the logic into the provider and improve a couple of things for robustness.  Please could you re-review this PR?

File: providers/default.rb [hunk 2]
```diff
@@ -191,13 +191,22 @@ def chef_backup_dir
   "#{chef_install_dir}.upgrade"
 end
 
+def chef_upgrade_log
+  "#{chef_install_dir}_upgrade.log"
```
Comment (tas50) [inline providers/default.rb]: are you trying to get chef_upgrade.log?

Comment (stuartpreston) [reply providers/default.rb]: Yes.

File: providers/default.rb [hunk 3]
```diff
@@ -250,7 +259,7 @@ def upgrade_start_time
 
 def prepare_windows
   copy_opt_chef(chef_install_dir, chef_backup_dir)
-  Kernel.spawn("c:/windows/system32/schtasks.exe /F /RU SYSTEM /create /sc once /ST \"#{upgrade_start_time}\" /tn Chef_upgrade /tr \"powershell.exe -ExecutionPolicy Bypass c:/opscode/chef_upgrade.ps1\"")
+  Kernel.spawn("c:/windows/system32/schtasks.exe /F /RU SYSTEM /create /sc once /ST \"#{upgrade_start_time}\" /tn Chef_upgrade /tr \"powershell.exe -ExecutionPolicy Bypass c:/opscode/chef_upgrade.ps1 > c:/opscode/chef_upgrade.log\"")
```
Comment (btm) [inline providers/default.rb]: `chef_upgrade.log` should be `#{chef_upgrade_log}`?
